### ISSUE TITLE
In 0.5.3, only displays first 11 lines in code cell until clicked

### ISSUE THREAD

**Issue by lspector** [benfb/gorilla-repl#8] opened 2018-11-28 20:42 UTC
The rest of the cell is blank, until I click in the cell, whereupon it displays.

This is under MacOS 12.12.6 in Safari 12.0.1 and Chrome 70.0.3538.110. Persists after system restart.

**Comment by benfb** [comment] 2020-06-14 00:00
I can't reproduce this anymore, so I'm going to assume 0.6.0 or the changes I'm working on now fixed this!

**Closed by benfb** 2020-06-14 00:00 UTC
